name: animated_button_bars
description: Animated button bars which can be used as bottom navigation bars as well as tab bar.
version: 0.0.1+1
homepage: https://github.com/jagritjkh/animated_button_bars.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: