name: animated_button_bars
description: Animated button bars which can be used as bottom navigation bars as well as tab bar.
version: 0.0.1+2
homepage: https://github.com/jagritjkh/animated_button_bars.git

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: